# Sobrescreve configurações para desenvolvimento local
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.com.gupify=DEBUG
logging.level.org.springframework.security=DEBUG

cors.allowed-origin=http://localhost:3000